#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sat May 30 17:54:33 CEST 2026
maven-metadata-central-snapshots.xml.error=
maven-metadata-central-snapshots.xml.lastUpdated=1780156473788
maven-metadata-jitpack.io.xml.error=
maven-metadata-jitpack.io.xml.lastUpdated=1773455113006
