// This file is autogenerated from scripts/generate-hljs-imports.js

import {hljs} from "@/utils/highlight"
import lang0 from 'highlight.js/lib/languages/abnf'
import lang1 from 'highlight.js/lib/languages/accesslog'
import lang2 from 'highlight.js/lib/languages/actionscript'
import lang3 from 'highlight.js/lib/languages/ada'
import lang4 from 'highlight.js/lib/languages/angelscript'
import lang5 from 'highlight.js/lib/languages/apache'
import lang6 from 'highlight.js/lib/languages/applescript'
import lang7 from 'highlight.js/lib/languages/arcade'
import lang8 from 'highlight.js/lib/languages/arduino'
import lang9 from 'highlight.js/lib/languages/armasm'
import lang10 from 'highlight.js/lib/languages/asciidoc'
import lang11 from 'highlight.js/lib/languages/aspectj'
import lang12 from 'highlight.js/lib/languages/autohotkey'
import lang13 from 'highlight.js/lib/languages/autoit'
import lang14 from 'highlight.js/lib/languages/avrasm'
import lang15 from 'highlight.js/lib/languages/awk'
import lang16 from 'highlight.js/lib/languages/axapta'
import lang17 from 'highlight.js/lib/languages/bash'
import lang18 from 'highlight.js/lib/languages/basic'
import lang19 from 'highlight.js/lib/languages/bnf'
import lang20 from 'highlight.js/lib/languages/brainfuck'
import lang21 from 'highlight.js/lib/languages/c'
import lang22 from 'highlight.js/lib/languages/cal'
import lang23 from 'highlight.js/lib/languages/capnproto'
import lang24 from 'highlight.js/lib/languages/ceylon'
import lang25 from 'highlight.js/lib/languages/clean'
import lang26 from 'highlight.js/lib/languages/clojure-repl'
import lang27 from 'highlight.js/lib/languages/clojure'
import lang28 from 'highlight.js/lib/languages/cmake'
import lang29 from 'highlight.js/lib/languages/coffeescript'
import lang30 from 'highlight.js/lib/languages/coq'
import lang31 from 'highlight.js/lib/languages/cos'
import lang32 from 'highlight.js/lib/languages/cpp'
import lang33 from 'highlight.js/lib/languages/crmsh'
import lang34 from 'highlight.js/lib/languages/crystal'
import lang35 from 'highlight.js/lib/languages/csharp'
import lang36 from 'highlight.js/lib/languages/csp'
import lang37 from 'highlight.js/lib/languages/css'
import lang38 from 'highlight.js/lib/languages/d'
import lang39 from 'highlight.js/lib/languages/dart'
import lang40 from 'highlight.js/lib/languages/delphi'
import lang41 from 'highlight.js/lib/languages/diff'
import lang42 from 'highlight.js/lib/languages/django'
import lang43 from 'highlight.js/lib/languages/dns'
import lang44 from 'highlight.js/lib/languages/dockerfile'
import lang45 from 'highlight.js/lib/languages/dos'
import lang46 from 'highlight.js/lib/languages/dsconfig'
import lang47 from 'highlight.js/lib/languages/dts'
import lang48 from 'highlight.js/lib/languages/dust'
import lang49 from 'highlight.js/lib/languages/ebnf'
import lang50 from 'highlight.js/lib/languages/elixir'
import lang51 from 'highlight.js/lib/languages/elm'
import lang52 from 'highlight.js/lib/languages/erb'
import lang53 from 'highlight.js/lib/languages/erlang-repl'
import lang54 from 'highlight.js/lib/languages/erlang'
import lang55 from 'highlight.js/lib/languages/excel'
import lang56 from 'highlight.js/lib/languages/fix'
import lang57 from 'highlight.js/lib/languages/flix'
import lang58 from 'highlight.js/lib/languages/fortran'
import lang59 from 'highlight.js/lib/languages/fsharp'
import lang60 from 'highlight.js/lib/languages/gams'
import lang61 from 'highlight.js/lib/languages/gauss'
import lang62 from 'highlight.js/lib/languages/gcode'
import lang63 from 'highlight.js/lib/languages/gherkin'
import lang64 from 'highlight.js/lib/languages/glsl'
import lang65 from 'highlight.js/lib/languages/go'
import lang66 from 'highlight.js/lib/languages/golo'
import lang67 from 'highlight.js/lib/languages/gradle'
import lang68 from 'highlight.js/lib/languages/graphql'
import lang69 from 'highlight.js/lib/languages/groovy'
import lang70 from 'highlight.js/lib/languages/haml'
import lang71 from 'highlight.js/lib/languages/handlebars'
import lang72 from 'highlight.js/lib/languages/haskell'
import lang73 from 'highlight.js/lib/languages/haxe'
import lang74 from 'highlight.js/lib/languages/hsp'
import lang75 from 'highlight.js/lib/languages/http'
import lang76 from 'highlight.js/lib/languages/hy'
import lang77 from 'highlight.js/lib/languages/inform7'
import lang78 from 'highlight.js/lib/languages/ini'
import lang79 from 'highlight.js/lib/languages/irpf90'
import lang80 from 'highlight.js/lib/languages/java'
import lang81 from 'highlight.js/lib/languages/javascript'
import lang82 from 'highlight.js/lib/languages/jboss-cli'
import lang83 from 'highlight.js/lib/languages/json'
import lang84 from 'highlight.js/lib/languages/julia-repl'
import lang85 from 'highlight.js/lib/languages/julia'
import lang86 from 'highlight.js/lib/languages/kotlin'
import lang87 from 'highlight.js/lib/languages/lasso'
import lang88 from 'highlight.js/lib/languages/latex'
import lang89 from 'highlight.js/lib/languages/ldif'
import lang90 from 'highlight.js/lib/languages/leaf'
import lang91 from 'highlight.js/lib/languages/less'
import lang92 from 'highlight.js/lib/languages/lisp'
import lang93 from 'highlight.js/lib/languages/livecodeserver'
import lang94 from 'highlight.js/lib/languages/livescript'
import lang95 from 'highlight.js/lib/languages/llvm'
import lang96 from 'highlight.js/lib/languages/lsl'
import lang97 from 'highlight.js/lib/languages/lua'
import lang98 from 'highlight.js/lib/languages/makefile'
import lang99 from 'highlight.js/lib/languages/markdown'
import lang100 from 'highlight.js/lib/languages/matlab'
import lang101 from 'highlight.js/lib/languages/mel'
import lang102 from 'highlight.js/lib/languages/mercury'
import lang103 from 'highlight.js/lib/languages/mipsasm'
import lang104 from 'highlight.js/lib/languages/mizar'
import lang105 from 'highlight.js/lib/languages/mojolicious'
import lang106 from 'highlight.js/lib/languages/monkey'
import lang107 from 'highlight.js/lib/languages/moonscript'
import lang108 from 'highlight.js/lib/languages/n1ql'
import lang109 from 'highlight.js/lib/languages/nestedtext'
import lang110 from 'highlight.js/lib/languages/nginx'
import lang111 from 'highlight.js/lib/languages/nim'
import lang112 from 'highlight.js/lib/languages/nix'
import lang113 from 'highlight.js/lib/languages/node-repl'
import lang114 from 'highlight.js/lib/languages/nsis'
import lang115 from 'highlight.js/lib/languages/objectivec'
import lang116 from 'highlight.js/lib/languages/ocaml'
import lang117 from 'highlight.js/lib/languages/openscad'
import lang118 from 'highlight.js/lib/languages/oxygene'
import lang119 from 'highlight.js/lib/languages/parser3'
import lang120 from 'highlight.js/lib/languages/perl'
import lang121 from 'highlight.js/lib/languages/pf'
import lang122 from 'highlight.js/lib/languages/php-template'
import lang123 from 'highlight.js/lib/languages/php'
import lang124 from 'highlight.js/lib/languages/plaintext'
import lang125 from 'highlight.js/lib/languages/pony'
import lang126 from 'highlight.js/lib/languages/powershell'
import lang127 from 'highlight.js/lib/languages/processing'
import lang128 from 'highlight.js/lib/languages/profile'
import lang129 from 'highlight.js/lib/languages/prolog'
import lang130 from 'highlight.js/lib/languages/properties'
import lang131 from 'highlight.js/lib/languages/protobuf'
import lang132 from 'highlight.js/lib/languages/puppet'
import lang133 from 'highlight.js/lib/languages/purebasic'
import lang134 from 'highlight.js/lib/languages/python-repl'
import lang135 from 'highlight.js/lib/languages/python'
import lang136 from 'highlight.js/lib/languages/q'
import lang137 from 'highlight.js/lib/languages/qml'
import lang138 from 'highlight.js/lib/languages/r'
import lang139 from 'highlight.js/lib/languages/reasonml'
import lang140 from 'highlight.js/lib/languages/rib'
import lang141 from 'highlight.js/lib/languages/roboconf'
import lang142 from 'highlight.js/lib/languages/routeros'
import lang143 from 'highlight.js/lib/languages/rsl'
import lang144 from 'highlight.js/lib/languages/ruby'
import lang145 from 'highlight.js/lib/languages/ruleslanguage'
import lang146 from 'highlight.js/lib/languages/rust'
import lang147 from 'highlight.js/lib/languages/sas'
import lang148 from 'highlight.js/lib/languages/scala'
import lang149 from 'highlight.js/lib/languages/scheme'
import lang150 from 'highlight.js/lib/languages/scilab'
import lang151 from 'highlight.js/lib/languages/scss'
import lang152 from 'highlight.js/lib/languages/shell'
import lang153 from 'highlight.js/lib/languages/smali'
import lang154 from 'highlight.js/lib/languages/smalltalk'
import lang155 from 'highlight.js/lib/languages/sml'
import lang156 from 'highlight.js/lib/languages/sql'
import lang157 from 'highlight.js/lib/languages/stan'
import lang158 from 'highlight.js/lib/languages/stata'
import lang159 from 'highlight.js/lib/languages/step21'
import lang160 from 'highlight.js/lib/languages/stylus'
import lang161 from 'highlight.js/lib/languages/subunit'
import lang162 from 'highlight.js/lib/languages/swift'
import lang163 from 'highlight.js/lib/languages/taggerscript'
import lang164 from 'highlight.js/lib/languages/tap'
import lang165 from 'highlight.js/lib/languages/tcl'
import lang166 from 'highlight.js/lib/languages/thrift'
import lang167 from 'highlight.js/lib/languages/tp'
import lang168 from 'highlight.js/lib/languages/twig'
import lang169 from 'highlight.js/lib/languages/typescript'
import lang170 from 'highlight.js/lib/languages/vala'
import lang171 from 'highlight.js/lib/languages/vbnet'
import lang172 from 'highlight.js/lib/languages/vbscript-html'
import lang173 from 'highlight.js/lib/languages/vbscript'
import lang174 from 'highlight.js/lib/languages/verilog'
import lang175 from 'highlight.js/lib/languages/vhdl'
import lang176 from 'highlight.js/lib/languages/vim'
import lang177 from 'highlight.js/lib/languages/wasm'
import lang178 from 'highlight.js/lib/languages/wren'
import lang179 from 'highlight.js/lib/languages/x86asm'
import lang180 from 'highlight.js/lib/languages/xl'
import lang181 from 'highlight.js/lib/languages/xml'
import lang182 from 'highlight.js/lib/languages/xquery'
import lang183 from 'highlight.js/lib/languages/yaml'
import lang184 from 'highlight.js/lib/languages/zephir'
import lang185 from 'highlight.js/lib/languages/sql'

hljs.registerLanguage('abnf', lang0)
hljs.registerLanguage('accesslog', lang1)
hljs.registerLanguage('actionscript', lang2)
hljs.registerLanguage('ada', lang3)
hljs.registerLanguage('angelscript', lang4)
hljs.registerLanguage('apache', lang5)
hljs.registerLanguage('applescript', lang6)
hljs.registerLanguage('arcade', lang7)
hljs.registerLanguage('arduino', lang8)
hljs.registerLanguage('armasm', lang9)
hljs.registerLanguage('asciidoc', lang10)
hljs.registerLanguage('aspectj', lang11)
hljs.registerLanguage('autohotkey', lang12)
hljs.registerLanguage('autoit', lang13)
hljs.registerLanguage('avrasm', lang14)
hljs.registerLanguage('awk', lang15)
hljs.registerLanguage('axapta', lang16)
hljs.registerLanguage('bash', lang17)
hljs.registerLanguage('basic', lang18)
hljs.registerLanguage('bnf', lang19)
hljs.registerLanguage('brainfuck', lang20)
hljs.registerLanguage('c', lang21)
hljs.registerLanguage('cal', lang22)
hljs.registerLanguage('capnproto', lang23)
hljs.registerLanguage('ceylon', lang24)
hljs.registerLanguage('clean', lang25)
hljs.registerLanguage('clojure-repl', lang26)
hljs.registerLanguage('clojure', lang27)
hljs.registerLanguage('cmake', lang28)
hljs.registerLanguage('coffeescript', lang29)
hljs.registerLanguage('coq', lang30)
hljs.registerLanguage('cos', lang31)
hljs.registerLanguage('cpp', lang32)
hljs.registerLanguage('crmsh', lang33)
hljs.registerLanguage('crystal', lang34)
hljs.registerLanguage('csharp', lang35)
hljs.registerLanguage('csp', lang36)
hljs.registerLanguage('css', lang37)
hljs.registerLanguage('d', lang38)
hljs.registerLanguage('dart', lang39)
hljs.registerLanguage('delphi', lang40)
hljs.registerLanguage('diff', lang41)
hljs.registerLanguage('django', lang42)
hljs.registerLanguage('dns', lang43)
hljs.registerLanguage('dockerfile', lang44)
hljs.registerLanguage('dos', lang45)
hljs.registerLanguage('dsconfig', lang46)
hljs.registerLanguage('dts', lang47)
hljs.registerLanguage('dust', lang48)
hljs.registerLanguage('ebnf', lang49)
hljs.registerLanguage('elixir', lang50)
hljs.registerLanguage('elm', lang51)
hljs.registerLanguage('erb', lang52)
hljs.registerLanguage('erlang-repl', lang53)
hljs.registerLanguage('erlang', lang54)
hljs.registerLanguage('excel', lang55)
hljs.registerLanguage('fix', lang56)
hljs.registerLanguage('flix', lang57)
hljs.registerLanguage('fortran', lang58)
hljs.registerLanguage('fsharp', lang59)
hljs.registerLanguage('gams', lang60)
hljs.registerLanguage('gauss', lang61)
hljs.registerLanguage('gcode', lang62)
hljs.registerLanguage('gherkin', lang63)
hljs.registerLanguage('glsl', lang64)
hljs.registerLanguage('go', lang65)
hljs.registerLanguage('golo', lang66)
hljs.registerLanguage('gradle', lang67)
hljs.registerLanguage('graphql', lang68)
hljs.registerLanguage('groovy', lang69)
hljs.registerLanguage('haml', lang70)
hljs.registerLanguage('handlebars', lang71)
hljs.registerLanguage('haskell', lang72)
hljs.registerLanguage('haxe', lang73)
hljs.registerLanguage('hsp', lang74)
hljs.registerLanguage('http', lang75)
hljs.registerLanguage('hy', lang76)
hljs.registerLanguage('inform7', lang77)
hljs.registerLanguage('ini', lang78)
hljs.registerLanguage('irpf90', lang79)
hljs.registerLanguage('java', lang80)
hljs.registerLanguage('javascript', lang81)
hljs.registerLanguage('jboss-cli', lang82)
hljs.registerLanguage('json', lang83)
hljs.registerLanguage('julia-repl', lang84)
hljs.registerLanguage('julia', lang85)
hljs.registerLanguage('kotlin', lang86)
hljs.registerLanguage('lasso', lang87)
hljs.registerLanguage('latex', lang88)
hljs.registerLanguage('ldif', lang89)
hljs.registerLanguage('leaf', lang90)
hljs.registerLanguage('less', lang91)
hljs.registerLanguage('lisp', lang92)
hljs.registerLanguage('livecodeserver', lang93)
hljs.registerLanguage('livescript', lang94)
hljs.registerLanguage('llvm', lang95)
hljs.registerLanguage('lsl', lang96)
hljs.registerLanguage('lua', lang97)
hljs.registerLanguage('makefile', lang98)
hljs.registerLanguage('markdown', lang99)
hljs.registerLanguage('matlab', lang100)
hljs.registerLanguage('mel', lang101)
hljs.registerLanguage('mercury', lang102)
hljs.registerLanguage('mipsasm', lang103)
hljs.registerLanguage('mizar', lang104)
hljs.registerLanguage('mojolicious', lang105)
hljs.registerLanguage('monkey', lang106)
hljs.registerLanguage('moonscript', lang107)
hljs.registerLanguage('n1ql', lang108)
hljs.registerLanguage('nestedtext', lang109)
hljs.registerLanguage('nginx', lang110)
hljs.registerLanguage('nim', lang111)
hljs.registerLanguage('nix', lang112)
hljs.registerLanguage('node-repl', lang113)
hljs.registerLanguage('nsis', lang114)
hljs.registerLanguage('objectivec', lang115)
hljs.registerLanguage('ocaml', lang116)
hljs.registerLanguage('openscad', lang117)
hljs.registerLanguage('oxygene', lang118)
hljs.registerLanguage('parser3', lang119)
hljs.registerLanguage('perl', lang120)
hljs.registerLanguage('pf', lang121)
hljs.registerLanguage('php-template', lang122)
hljs.registerLanguage('php', lang123)
hljs.registerLanguage('plaintext', lang124)
hljs.registerLanguage('pony', lang125)
hljs.registerLanguage('powershell', lang126)
hljs.registerLanguage('processing', lang127)
hljs.registerLanguage('profile', lang128)
hljs.registerLanguage('prolog', lang129)
hljs.registerLanguage('properties', lang130)
hljs.registerLanguage('protobuf', lang131)
hljs.registerLanguage('puppet', lang132)
hljs.registerLanguage('purebasic', lang133)
hljs.registerLanguage('python-repl', lang134)
hljs.registerLanguage('python', lang135)
hljs.registerLanguage('q', lang136)
hljs.registerLanguage('qml', lang137)
hljs.registerLanguage('r', lang138)
hljs.registerLanguage('reasonml', lang139)
hljs.registerLanguage('rib', lang140)
hljs.registerLanguage('roboconf', lang141)
hljs.registerLanguage('routeros', lang142)
hljs.registerLanguage('rsl', lang143)
hljs.registerLanguage('ruby', lang144)
hljs.registerLanguage('ruleslanguage', lang145)
hljs.registerLanguage('rust', lang146)
hljs.registerLanguage('sas', lang147)
hljs.registerLanguage('scala', lang148)
hljs.registerLanguage('scheme', lang149)
hljs.registerLanguage('scilab', lang150)
hljs.registerLanguage('scss', lang151)
hljs.registerLanguage('shell', lang152)
hljs.registerLanguage('smali', lang153)
hljs.registerLanguage('smalltalk', lang154)
hljs.registerLanguage('sml', lang155)
hljs.registerLanguage('sql', lang156)
hljs.registerLanguage('stan', lang157)
hljs.registerLanguage('stata', lang158)
hljs.registerLanguage('step21', lang159)
hljs.registerLanguage('stylus', lang160)
hljs.registerLanguage('subunit', lang161)
hljs.registerLanguage('swift', lang162)
hljs.registerLanguage('taggerscript', lang163)
hljs.registerLanguage('tap', lang164)
hljs.registerLanguage('tcl', lang165)
hljs.registerLanguage('thrift', lang166)
hljs.registerLanguage('tp', lang167)
hljs.registerLanguage('twig', lang168)
hljs.registerLanguage('typescript', lang169)
hljs.registerLanguage('vala', lang170)
hljs.registerLanguage('vbnet', lang171)
hljs.registerLanguage('vbscript-html', lang172)
hljs.registerLanguage('vbscript', lang173)
hljs.registerLanguage('verilog', lang174)
hljs.registerLanguage('vhdl', lang175)
hljs.registerLanguage('vim', lang176)
hljs.registerLanguage('wasm', lang177)
hljs.registerLanguage('wren', lang178)
hljs.registerLanguage('x86asm', lang179)
hljs.registerLanguage('xl', lang180)
hljs.registerLanguage('xml', lang181)
hljs.registerLanguage('xquery', lang182)
hljs.registerLanguage('yaml', lang183)
hljs.registerLanguage('zephir', lang184)
hljs.registerLanguage('pgsql', lang185)
